[[SwiftShader]]
arch = "x86_64"
git-tree-sha1 = "571b92e4e1a0474d579859eb3ceb89f7c9476529"
os = "macos"

    [[SwiftShader.download]]
    sha256 = "356c6ee05bc3dc0e9c21a7c1d96d1e7ce42e6f36f281829d3b65aeb7046694ed"
    url = "https://github.com/JuliaBinaryWrappers/SwiftShader_jll.jl/releases/download/SwiftShader-v0.1.0+0/SwiftShader.v0.1.0.x86_64-apple-darwin.tar.gz"
[[SwiftShader]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e94aafd7f2a12b0bcb1fa012f9525665473672b3"
libc = "glibc"
os = "linux"

    [[SwiftShader.download]]
    sha256 = "a48671e9298a44cccbf163d93b0c9e76a65c5458ab2b15b90a0efb6a54c87746"
    url = "https://github.com/JuliaBinaryWrappers/SwiftShader_jll.jl/releases/download/SwiftShader-v0.1.0+0/SwiftShader.v0.1.0.x86_64-linux-gnu-cxx03.tar.gz"
[[SwiftShader]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "92ef6528ec0492010323f96b079eb94fd838b31e"
libc = "glibc"
os = "linux"

    [[SwiftShader.download]]
    sha256 = "6ee57717373b426ac52372feb341899ea780f99fb819c62fb9f2e0fe83ab9254"
    url = "https://github.com/JuliaBinaryWrappers/SwiftShader_jll.jl/releases/download/SwiftShader-v0.1.0+0/SwiftShader.v0.1.0.x86_64-linux-gnu-cxx11.tar.gz"
