# Autogenerated wrapper script for SwiftShader_jll for aarch64-apple-darwin
export libvk_swiftshader, libvulkan

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("SwiftShader")
JLLWrappers.@declare_library_product(libvk_swiftshader, "@rpath/libvk_swiftshader.dylib")
JLLWrappers.@declare_library_product(libvulkan, "@rpath/libvk_swiftshader.dylib")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libvk_swiftshader,
        "lib/libvk_swiftshader.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libvulkan,
        "lib/libvulkan.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
